**Pytorch tensor**

In [3]:
from __future__ import print_function  # 在python2的环境下，超前使用python3的print函数。
import torch
import numpy as np

# 张量 Tensors

torch.DoubleTensor   
torch.LongTensor  
torch.FloatTensor     
torch.CharTensor   
torch.IntTensor    
torch.ShortTensor    
torch.TensorType   

In [29]:
isinstance(a,torch.LongTensor)

False

* 判断是否是tensor

In [7]:
torch.is_tensor([1,2])

False

* 统计tensor的元素个数

In [8]:
torch.numel(torch.randn(2,3))

6

# 创建tensor 

## torch.eye 对角矩阵

In [9]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## from_numpy  转换 

In [10]:
a = np.array([[1,2],[3,5]])
b = torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 5]], dtype=torch.int32)

## torch.linspace

In [13]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## torch.logspace(start,end,steps)

包含在区间 10start 和 10end上以对数刻度均匀间隔的steps个点

In [14]:
torch.logspace(0,1,5)

tensor([ 1.0000,  1.7783,  3.1623,  5.6234, 10.0000])

##  torch.ones  torch.zeros  torch.empty

In [20]:
print(torch.ones(2,5))
print(torch.zeros(2,6))
print(torch.empty(2,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


## torch.rand torch.randn torch.randperm
* torch.rand 0-1之间均匀分布
* torch.randn 均值0 方差1 的正态分布
* torch.randperm 随机整数

In [24]:
print(torch.rand(3,5))
print(torch.randn(2,4))
print(torch.randperm(3))

tensor([[0.3175, 0.8111, 0.9739, 0.7672, 0.5701],
        [0.8480, 0.1516, 0.2500, 0.6397, 0.7502],
        [0.8800, 0.3569, 0.6821, 0.4749, 0.7194]])
tensor([[-1.4261,  1.0244, -2.0498, -0.4911],
        [ 0.0810,  0.4826,  0.7082, -0.5161]])
tensor([2, 0, 1])


## torch.arange
与 torch.linspace 类似 torch.linspace 中的steps 指个数，torch.arange 中的step 指步长


In [25]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

## torch.**_like 
* torch.ones_like 
* torch.empty_like
* torch.rand_like
* torch.zeros_like

In [31]:
a = torch.rand(4,3)
b= torch.zeros_like(a)
c= torch.ones_like(a)
d= torch.empty_like(a)
e= torch.rand_like(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0693, 0.2749, 0.8524],
        [0.4724, 0.7952, 0.8751],
        [0.9834, 0.8985, 0.1532],
        [0.7223, 0.2870, 0.5356]])
