In [2]:
from __future__ import print_function
import torch
import numpy as np

# 拼接

## torch.cat
torch.cat(inputs,dimens=0)

In [4]:
x = torch.ones(2,4)
torch.cat((x,x))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## torch.stack
torch.stack(sequence, dim=0)   
在维度上连接（concatenate）若干个张量。(这些张量形状相同）。

In [40]:
a = torch.arange(0,8).view(2,4)
b = torch.arange(10,18).view(2,4)
c = torch.arange(100,108).view(2,4)
x =torch.stack((a,b,c),dim=0)
y = torch.stack((a,b,b),dim=1)
z = torch.stack((a,b,b),dim=2)
print(x.size(),y.size(),z.size())

torch.Size([3, 2, 4]) torch.Size([2, 3, 4]) torch.Size([2, 4, 3])


# 分块

## torch.chunk
torch.chunk(tensor, chunks, dim=0) chunks 分块个数

In [9]:
a= torch.rand(6,8)
print(torch.chunk(a,2))

(tensor([[0.0631, 0.2014, 0.4618, 0.0386, 0.7897, 0.4091, 0.0462, 0.0468],
        [0.1436, 0.9544, 0.0616, 0.6193, 0.8887, 0.9349, 0.9854, 0.4089],
        [0.8058, 0.4348, 0.0617, 0.0345, 0.3419, 0.8109, 0.1779, 0.0532]]), tensor([[0.3001, 0.1326, 0.4118, 0.3709, 0.3354, 0.0811, 0.3897, 0.4254],
        [0.1158, 0.3227, 0.7693, 0.8539, 0.0362, 0.6780, 0.2802, 0.1158],
        [0.5312, 0.5786, 0.5035, 0.8330, 0.2437, 0.6671, 0.9198, 0.5265]]))


In [18]:
print(torch.chunk(a,6))

(tensor([[0.0631, 0.2014, 0.4618, 0.0386, 0.7897, 0.4091, 0.0462, 0.0468]]), tensor([[0.1436, 0.9544, 0.0616, 0.6193, 0.8887, 0.9349, 0.9854, 0.4089]]), tensor([[0.8058, 0.4348, 0.0617, 0.0345, 0.3419, 0.8109, 0.1779, 0.0532]]), tensor([[0.3001, 0.1326, 0.4118, 0.3709, 0.3354, 0.0811, 0.3897, 0.4254]]), tensor([[0.1158, 0.3227, 0.7693, 0.8539, 0.0362, 0.6780, 0.2802, 0.1158]]), tensor([[0.5312, 0.5786, 0.5035, 0.8330, 0.2437, 0.6671, 0.9198, 0.5265]]))


## torch.split
torch.split(tensor, split_size, dim=0)  #split_size 最后一块可能小于split_size 

In [16]:
torch.split(a,4) 

(tensor([[0.0631, 0.2014, 0.4618, 0.0386, 0.7897, 0.4091, 0.0462, 0.0468],
         [0.1436, 0.9544, 0.0616, 0.6193, 0.8887, 0.9349, 0.9854, 0.4089],
         [0.8058, 0.4348, 0.0617, 0.0345, 0.3419, 0.8109, 0.1779, 0.0532],
         [0.3001, 0.1326, 0.4118, 0.3709, 0.3354, 0.0811, 0.3897, 0.4254]]),
 tensor([[0.1158, 0.3227, 0.7693, 0.8539, 0.0362, 0.6780, 0.2802, 0.1158],
         [0.5312, 0.5786, 0.5035, 0.8330, 0.2437, 0.6671, 0.9198, 0.5265]]))

# 索引

## torch.gather
torch.gather(input, dim, index, out=None) → Tensor   
沿给定轴dim，将输入索引张量index指定位置的值进行聚合

In [22]:
t= torch.tensor([[1,2],[3,4]])
print(t)
torch.gather(t,1,torch.LongTensor([[0,0],[1,0]]))

tensor([[1, 2],
        [3, 4]])


tensor([[1, 1],
        [4, 3]])

In [21]:
torch.gather(t,0,torch.LongTensor([[0,0],[1,0]]))
# 理解 dim =0  从左往右 分成列，在从上向下去取index 位置  返回结果的size与index的维度相同
# 理解 dim =1  从上往下 分成行，在从左向右取index 位置  返回结果的size与index的维度相同

tensor([[1, 2],
        [3, 2]])

In [26]:
t2= torch.tensor([[1,2],[3,4],[5,6]])
print(t2)
torch.gather(t2,0,torch.LongTensor([[1,2]]))
torch.gather(t2,0,torch.LongTensor([[1,2],[0,1]]))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[3, 6],
        [1, 4]])

## torch.index_select
torch.index_select(input, dim, index, out=None) → Tensor

In [27]:
torch.index_select(t2,1,torch.LongTensor([1]))

tensor([[2],
        [4],
        [6]])

In [28]:
torch.index_select(t2,0,torch.LongTensor([1,2]))

tensor([[3, 4],
        [5, 6]])

##  torch.mask_select
torch.masked_select(input, mask, out=None) → Tensor    
输入张量对应位置的元素是否保留，既然是一一对应的关系，这就需要传入 mask 中的布尔张量和传入 input 中的输入张量形状要相同

In [29]:
x = torch.randn(3,4)
mask = x.ge(0)
print(x)
print(mask)

tensor([[ 0.8483,  0.4649, -0.2564, -0.1502],
        [-0.7617, -0.3410,  0.5247,  2.0766],
        [ 0.9188, -0.0397, -0.7750,  1.2267]])
tensor([[ True,  True, False, False],
        [False, False,  True,  True],
        [ True, False, False,  True]])


In [30]:
print(torch.masked_select(x,mask))

tensor([0.8483, 0.4649, 0.5247, 2.0766, 0.9188, 1.2267])


# 换位

## torch.squeeze torch.unsqueeze

In [36]:
print(x.size())
y = torch.unsqueeze(x,1)
print(y.size())
z = x.squeeze()
print(z.size())

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


## torch.t torch.transpose 


In [42]:
torch.t(a).size()

torch.Size([4, 2])

In [43]:
torch.transpose(a,1,0).size()

torch.Size([4, 2])

## permute 

In [47]:
print(a.size())
print(a.permute(1,0))
x = torch.randn(2,3,4)
print(x.permute(1,2,0).size())

torch.Size([2, 4])
tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])
torch.Size([3, 4, 2])
