In [1]:
import torch
import numpy as np

In [ ]:
# []
# :  start:end:step
# ...
# index_select
# mask

In [2]:
a = torch.Tensor(4,3,28,28)
print(a[0].shape)
print(a[0,1].shape)
print(a[0,2,3].shape)
print(a[0,1,1,1].shape)

torch.Size([3, 28, 28])
torch.Size([28, 28])
torch.Size([28])
torch.Size([])


In [8]:
a=torch.Tensor(4,3,28,28)
print(a[:3,1:].shape)
print(a[:3,:3,0:28:2].shape)

torch.Size([3, 2, 28, 28])
torch.Size([3, 3, 14, 28])


In [12]:
a=torch.Tensor(4,3,28,28)
print(a[...,0:28:8,1].shape)

torch.Size([4, 3, 4])


In [15]:
print(a.index_select(0,torch.tensor([0,2])).shape)
# index_select (axis , values)
print(a.index_select(3,torch.tensor([0,2,3,5])).shape)

torch.Size([2, 3, 28, 28])
torch.Size([4, 3, 28, 4])


In [20]:
# 可以获取满足一些条件的值的位置索引，然后用这个索引去取出这些位置的元素
a = torch.randn(3,4)
print(a)
masked = a.ge(0.5)
print(masked)
print(a[masked])

tensor([[ 1.9184, -0.5270, -0.1989, -0.7034],
        [-0.4337,  0.4029,  0.2309, -0.4172],
        [-0.2134, -0.1171, -1.6370, -0.2585]])
tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([1.9184])
