In [1]:
import torch
import numpy as np

## torch.manual_seed
设定生成随机数的种子

In [ ]:
torch.manual_seed(12)

In [4]:
torch.get_num_threads()

2

## torch.bernoulli
torch.bernoulli(input, out=None) → Tensor   
从伯努利分布中抽取二元随机数(0 或者 1)。
输入张量须包含用于抽取上述二元随机值的概率。 因此，输入中的所有值都必须在［0,1］区间

In [9]:
a = torch.rand(3,5)
torch.bernoulli(a)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]])

## torch.multinomial
torch.multinomial(input, num_samples,replacement=False, out=None)     
每行包含从input相应行中定义的多项分布中抽取的num_samples个样本。   
参数num_samples必须小于input长度

In [13]:
weights = torch.Tensor([0,3,10,0])
torch.multinomial(weights,4)

tensor([2, 1, 0, 3])

## torch.noimal
torch.normal(means, std, out=None)   
返回一个张量，包含从给定参数means,std的离散正态分布中抽取随机数。 均值means是一个张量，包含每个输出元素相关的正态分布的均值。 std是一个张量，包含每个输出元素相关的正态分布的标准差。 均值和标准差的形状不须匹配，但每个张量的元素个数须相同。

In [28]:
torch.normal(torch.arange(1.0, 11.0),torch.arange(1.0, 0., -0.1))

tensor([ 1.4772,  0.8330,  3.0188,  5.6601,  5.3235,  6.2448,  6.9563,  7.6746,
         9.0971, 10.2051])

In [27]:
torch.normal(1.0,torch.arange(1.0, 0., -0.1))

tensor([2.3182, 1.1446, 1.7349, 1.3361, 1.1172, 0.7796, 1.2376, 1.2531, 1.0176,
        0.8748])

## torch.save  torch.load