In [2]:
import torch
import numpy as np

# Pointwise Ops

## **三角函数**
* torch.acos
* torch.asin
* torch.atan
* torch.cos 
* torch.cosh 双曲余弦
* torch.sin 
* torch.sinh 双曲正弦
* torch.tan 
* torch.tanh 双曲正切

## **常用函数** 
* torch.add
* torch.sub
* torch.mul 
  torch.mul(input, value, out=None) 标量值value乘以input的每个元素
* torch.div    
   torch.div(input, value, out=None) 逐元素除以标量值
* torch.exp  
* torch.log 
* torch.pow    
  torch.pow(input, exponent, out=None) 幂值
* torch.sqrt 平方根

## **其他函数**

* torch.sigmod 
* torch.clamp   
  torch.clamp(input, min, max, out=None)  夹紧到区间 [min,max]
  
  
* torch.abs
* torch.neg 按元素取负 
* torch.sign 正负 


* torch.ceil  向上取整
* torch.floor 向下取整


* torch.frac 取分数部分
* torch.trunc 截断值 取整


* torch.fmod 除法余数

* torch.round 舍入到最近的整数


* torch.reciprocal 倒数
* torch.rsqrt 平方根倒数

In [4]:
a = torch.randn(2,3)
print(a)
print(torch.frac(a))
print(torch.trunc(a))

tensor([[-1.3271,  0.4525,  0.0740],
        [ 0.1732,  0.2933,  1.9344]])
tensor([[-0.3271,  0.4525,  0.0740],
        [ 0.1732,  0.2933,  0.9344]])
tensor([[-1.,  0.,  0.],
        [ 0.,  0.,  1.]])


In [7]:
1/a,a.reciprocal()

(tensor([[-0.7535,  2.2101, 13.5068],
         [ 5.7721,  3.4093,  0.5170]]),
 tensor([[-0.7535,  2.2101, 13.5068],
         [ 5.7721,  3.4093,  0.5170]]))

# Reduction Ops

* torch.mean
* torch.median
* torch.mode 众数
* torch.prod 积
* torch.std
* torch.sum
* torch.var
   
* torch.cumprod 累积
* torch.cumsum 累加
* torch.norm 
    torch.norm(input, p=2) p范数
* torch.dist 
    torch.dist(input, other, p=2, out=None)  (input- other) 的范数

# Comparison Ops 比较操作 

* torch.eq -->Tensor  逐元素相等
* torch.equal  相同的形状和元素值
* torch.ge     >=
* torch.gt     >
* torch.le     <=
* torch.lt     <
* torch.ne     !=
* torch.max 
* torch.min 
* torch.sort   
   torch.sort(input, dim=None, descending=False, out=None) -> (Tensor, LongTensor)  
    对输入张量input沿着指定维按升序排序。如果不给定dim，则默认为输入的最后一维。  
    如果指定参数descending为True，则按降序排序
    
* torch.topk   
    torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) -> (Tensor, LongTensor)
    沿给定dim维度返回输入张量input中 k 个最大值。 如果不指定dim，则默认为input的最后一维。 
    如果为largest为 False ，则返回最小的 k 个值。

In [13]:
torch.equal(torch.Tensor([1,3]),torch.Tensor([1,2]))

False

In [8]:
torch.eq(torch.Tensor([1,2]),torch.Tensor([1,2]))

tensor([True, True])

# Other Operations

* torch.diag
         torch.diag(input, diagonal=0, out=None) → Tensor
         如果输入是一个向量(1D 张量)，则返回一个以input为对角线元素的2D方阵
         如果输入是一个矩阵(2D 张量)，则返回一个包含input对角线元素的1D张量
        diagonal = 0, 主对角线
        diagonal > 0, 主对角线之上
        diagonal < 0, 主对角线之下
* torch.trace   输入2维矩阵对角线元素的和(迹)
* torch.addbmm 
       torch.addbmm(beta=1, mat, alpha=1, batch1, batch2, out=None) → Tensor
       res=(beta∗M)+(alpha∗sum(batch1i@batch2i,i=0,b))
* torch.addmm
       torch.addmm(beta=1, mat, alpha=1, mat1, mat2, out=None) → Tensor
       out=(beta∗M)+(alpha∗mat1@mat2)
* torch.addmv
       torch.addmv(beta=1, tensor, alpha=1, mat, vec, out=None) → Tensor
         out=(beta∗tensor)+(alpha∗(mat@vec))
* torch.bmm
        torch.bmm(batch1, batch2, out=None) → Tensor 批矩阵乘操作
        batch1: b×n×m    batch2 : b×m×p  out: b×n×p
                
* torch.dot  1-D 向量 点乘
* torch.eig  特征值和特征向量
* torch.ger 
        torch.ger(vec1, vec2, out=None) → Tensor
        计算两向量vec1,vec2的张量积。如果vec1的长度为n,vec2长度为m，则输出out应为形如n x m的矩阵
* torch.mm 矩阵相乘
* torch.mv 对矩阵mat和向量vec进行相乘
* torch.svd   A 进行奇异值分解