# Tensor的其他函数  
可以用Tensor.Function 形式调用

In [6]:
import torch 

* cpu  
* cuda 

* data_ptr  
返回tensor第一个元素的地址

In [8]:
x = torch.randn(3,3)
x.data_ptr()

1891953156800

* element_size   
返回单个元素的字节大小

In [10]:
x.element_size()

4

* expand(*sizes)   
单个维度扩大为更大的尺寸
* expand_as(tensor)   == expand(tenser.size())   

In [24]:
print(x.size())
x.view(1,3,3)
y =x.expand(4,3,3)
print(y.size())
print(y)

torch.Size([3, 3])
torch.Size([4, 3, 3])
tensor([[[-0.6773, -1.8100, -0.2612],
         [-0.1534, -0.4716, -0.1023],
         [ 1.5681,  0.2160, -0.9568]],

        [[-0.6773, -1.8100, -0.2612],
         [-0.1534, -0.4716, -0.1023],
         [ 1.5681,  0.2160, -0.9568]],

        [[-0.6773, -1.8100, -0.2612],
         [-0.1534, -0.4716, -0.1023],
         [ 1.5681,  0.2160, -0.9568]],

        [[-0.6773, -1.8100, -0.2612],
         [-0.1534, -0.4716, -0.1023],
         [ 1.5681,  0.2160, -0.9568]]])


* fill_(value)
* float()
* int()
* long()
* short()
* numpy()
* is_contiguous()
* is_cuda()
* permute()
* size()

In [19]:
y.permute(2,1,0).size()

torch.Size([3, 3, 4])

* repeat()

In [23]:
print(x)
x.repeat(2,2)

tensor([[-0.6773, -1.8100, -0.2612],
        [-0.1534, -0.4716, -0.1023],
        [ 1.5681,  0.2160, -0.9568]])


tensor([[-0.6773, -1.8100, -0.2612, -0.6773, -1.8100, -0.2612],
        [-0.1534, -0.4716, -0.1023, -0.1534, -0.4716, -0.1023],
        [ 1.5681,  0.2160, -0.9568,  1.5681,  0.2160, -0.9568],
        [-0.6773, -1.8100, -0.2612, -0.6773, -1.8100, -0.2612],
        [-0.1534, -0.4716, -0.1023, -0.1534, -0.4716, -0.1023],
        [ 1.5681,  0.2160, -0.9568,  1.5681,  0.2160, -0.9568]])

* resize()
* tolist()

* split()   
split(split_size, dim=0)

In [34]:
y.split(4,0)

(tensor([[[-0.6773, -1.8100, -0.2612],
          [-0.1534, -0.4716, -0.1023],
          [ 1.5681,  0.2160, -0.9568]],
 
         [[-0.6773, -1.8100, -0.2612],
          [-0.1534, -0.4716, -0.1023],
          [ 1.5681,  0.2160, -0.9568]],
 
         [[-0.6773, -1.8100, -0.2612],
          [-0.1534, -0.4716, -0.1023],
          [ 1.5681,  0.2160, -0.9568]],
 
         [[-0.6773, -1.8100, -0.2612],
          [-0.1534, -0.4716, -0.1023],
          [ 1.5681,  0.2160, -0.9568]]]),)

In [28]:
y.size()


torch.Size([4, 3, 3])