In [1]:
import torch
import numpy as np

# cat

In [8]:
# 保证其它维度的size是相同的。
a = torch.randn(4,3,4)
b = torch.randn(5,3,4)
c = torch.cat([a,b],dim=0)
print(c.shape)

torch.Size([9, 3, 4])


# stack

In [9]:
# 新增维度 
a = torch.randn(4,3,4)
b = torch.randn(4,3,4)
c = torch.stack([a,b],dim=1)
print(c.shape)

torch.Size([4, 2, 3, 4])


# split

In [16]:
# 可以指定拆分后的几个Tensor各取多少长度，或者指定每个Tensor取多少长度。
a = torch.randn(4,3,28,28)
print(a.shape)
c ,d = a.split(2,dim=0)
print(c.shape,d.shape)
g,h,i= a.split([1,2,25],dim=2)
print(g.shape,h.shape,i.shape)

torch.Size([4, 3, 28, 28])
torch.Size([2, 3, 28, 28]) torch.Size([2, 3, 28, 28])
torch.Size([4, 3, 1, 28]) torch.Size([4, 3, 2, 28]) torch.Size([4, 3, 25, 28])


# chunk

In [21]:
# 给定在指定的维度上要拆分得的份数
print(a.shape)
print(a.chunk(5,dim=3)[4].shape)

torch.Size([4, 3, 28, 28])
torch.Size([4, 3, 28, 4])


# + - * / 

In [23]:
a = torch.rand(3,4)
b = torch.rand(4)
c = a+b # add
print(c.shape)

d = a-b # sub
print(d.shape)

e = a*b  # mul
print(e.shape)

g = a/d # div
print(g.shape)

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])


# mm matmul @

In [32]:
# mm 只适用于2维
a = torch.rand(3,4)
b = torch.rand(4,1)
print(a.mm(b).shape)

a = torch.rand(3,4,6)
b = torch.rand(1,6,3)
# 后两个维度作为 矩阵进行运算 可以适用broadcast
print(a.matmul(b).shape)
print((a@b).shape)

torch.Size([3, 1])
torch.Size([3, 4, 3])
torch.Size([3, 4, 3])


# pow sqrt rsqrt

In [33]:
a = torch.full([4],10)

c = a.pow(2)
print(c)

d = a.sqrt()
print(d)

e = a.rsqrt()
print(e)

tensor([100., 100., 100., 100.])
tensor([3.1623, 3.1623, 3.1623, 3.1623])
tensor([0.3162, 0.3162, 0.3162, 0.3162])


# exp log floor ceil trunc frac  round

In [37]:
a = torch.exp(torch.ones(2,2))
print(a)
b = torch.log(a)
print(b)
a = torch.tensor(3.1415)
print(a.floor(),a.ceil(),a.trunc(),a.frac())

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[1., 1.],
        [1., 1.]])
tensor(3.) tensor(4.) tensor(3.) tensor(0.1415)


In [43]:
print(a.round(),(a*torch.tensor(10.)).round())

tensor(3.) tensor(31.)


# grad.clamp

In [47]:
# Tensor中的元素进行范围过滤，不符合条件的可以把它变换到范围内部（边界）上，常用于梯度裁剪（gradient clipping）
a = torch.rand(2,3) * 15
print(a)
a.clamp()
print(a.clamp(10)) # 最小值
print(a.clamp(5,10))

tensor([[ 0.9472,  1.8314, 14.8476],
        [ 5.8018,  8.8303, 14.5284]])
tensor([[10.0000, 10.0000, 14.8476],
        [10.0000, 10.0000, 14.5284]])
tensor([[ 5.0000,  5.0000, 10.0000],
        [ 5.8018,  8.8303, 10.0000]])
