In [2]:
import torch 
import numpy as np

In [ ]:
# norm 范数 
# sum max min prod 
# argmin argmax 
# topk
# where gather 

# norm 

In [10]:
a =torch.randn(3,5)
a =torch.ones(3,5)
print(a.norm(1,dim=0).shape,a.norm(1,dim=0))
print(a.norm(1,dim=1).shape)
print(a.norm(2,dim=0).shape)
print(a.norm(1).shape)

torch.Size([5]) tensor([3., 3., 3., 3., 3.])
torch.Size([3])
torch.Size([5])
torch.Size([])


# sum max min prod 

In [13]:
a =torch.randn(3,5)
print(a.sum(),a.min(),a.prod()) # prod 累计值 也可以指定dim
print(a)

tensor(5.5046) tensor(-0.8565) tensor(-7.2106e-06)
tensor([[ 0.2038,  0.1896, -0.8313,  1.9990, -0.6776],
        [ 0.3438, -0.0460,  0.1355,  0.8630,  0.3408],
        [ 0.4204, -0.4637,  0.4597, -0.8565,  3.4240]])


# argmax argmin

In [16]:
a =torch.randn(3,5)
print(a)
print(a.argmax()) # 打平之后的位置索引
print(a.argmin())# 打平之后的位置索引
print(a.argmax(dim=0))
print(a.argmin(dim=0))
print(a.argmin(dim=1))

tensor([[-0.9817, -0.8484,  0.2975, -1.1879, -0.0998],
        [ 1.3036, -0.9048,  0.8158,  1.2423,  0.9522],
        [-0.5522,  0.0352, -0.1532, -0.3450, -0.7925]])
tensor(5)
tensor(3)
tensor([1, 2, 1, 1, 1])
tensor([0, 1, 2, 0, 2])
tensor([3, 1, 4])


In [19]:
# 使用keepdim=True可以保持应有的dim，即仅仅是将求最值的那个dim的size变成了1
print(a.argmin(dim=0,keepdim=True))
print(a.min(dim=0,keepdim=True))
print(a.argmin(dim=0,keepdim=True).shape)

tensor([[0, 1, 2, 0, 2]])
torch.return_types.min(
values=tensor([[-0.9817, -0.9048, -0.1532, -1.1879, -0.7925]]),
indices=tensor([[0, 1, 2, 0, 2]]))
torch.Size([1, 5])


# topk

In [30]:
# 求最小的k个，只要使用参数largest=False。
print(a)
print(a.topk(2,dim=1)[1])
print(a.topk(1,dim=1,largest=False)[1])

tensor([[-0.9817, -0.8484,  0.2975, -1.1879, -0.0998],
        [ 1.3036, -0.9048,  0.8158,  1.2423,  0.9522],
        [-0.5522,  0.0352, -0.1532, -0.3450, -0.7925]])
tensor([[2, 4],
        [0, 3],
        [1, 2]])
tensor([[3],
        [1],
        [4]])


# where 

In [33]:
cond = torch.tensor([[0.3,0.7],[0.1,0.9]])
a = torch.arange(0,4).reshape(2,2)
print(a)
b = torch.arange(4,8).reshape(2,2)
print(b)
torch.where(cond>0.5,a,b)

tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])


tensor([[4, 1],
        [6, 3]])

# gather 

In [47]:
# gather(input, dim, index, out=None, sparse_grad=False) -> Tensor
# 使用torch.gather(input,dim,index)对元素实现一个查表映射的操作
prob = torch.randn(4, 10)
_, idx = prob.topk(3, dim=1)
print(idx)
ipt = torch.arange(10) + 100
print(ipt)  # 用于将idx的0~9映射到100~109
out = torch.gather(ipt.expand(4, 10), dim=1, index=idx.long())
print(out)
ipt.expand(4, 10)

tensor([[3, 7, 4],
        [8, 0, 4],
        [2, 9, 7],
        [3, 8, 7]])
tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])
tensor([[103, 107, 104],
        [108, 100, 104],
        [102, 109, 107],
        [103, 108, 107]])


tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])