In [1]:
import torch
import numpy as np
from torch.nn import functional as F

In [2]:
# sigmoid tanh relu  softmax
# torch.nn.functional下，可以直接使用  mse_loss cross_entorpy_loss
# torch.autograd.grad  loss .backward 

# sigmoid tanh relu  softmax

In [3]:
a = torch.linspace(-10,10,51)
print(a)
print(torch.sigmoid(a))

tensor([-10.0000,  -9.6000,  -9.2000,  -8.8000,  -8.4000,  -8.0000,  -7.6000,
         -7.2000,  -6.8000,  -6.4000,  -6.0000,  -5.6000,  -5.2000,  -4.8000,
         -4.4000,  -4.0000,  -3.6000,  -3.2000,  -2.8000,  -2.4000,  -2.0000,
         -1.6000,  -1.2000,  -0.8000,  -0.4000,   0.0000,   0.4000,   0.8000,
          1.2000,   1.6000,   2.0000,   2.4000,   2.8000,   3.2000,   3.6000,
          4.0000,   4.4000,   4.8000,   5.2000,   5.6000,   6.0000,   6.4000,
          6.8000,   7.2000,   7.6000,   8.0000,   8.4000,   8.8000,   9.2000,
          9.6000,  10.0000])
tensor([4.5398e-05, 6.7724e-05, 1.0103e-04, 1.5071e-04, 2.2482e-04, 3.3535e-04,
        5.0020e-04, 7.4603e-04, 1.1125e-03, 1.6588e-03, 2.4726e-03, 3.6842e-03,
        5.4863e-03, 8.1626e-03, 1.2128e-02, 1.7986e-02, 2.6597e-02, 3.9166e-02,
        5.7324e-02, 8.3173e-02, 1.1920e-01, 1.6798e-01, 2.3148e-01, 3.1003e-01,
        4.0131e-01, 5.0000e-01, 5.9869e-01, 6.8997e-01, 7.6852e-01, 8.3202e-01,
        8.8080e-01, 9.168

In [4]:
print(torch.tanh(a))

tensor([-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
        -1.0000, -1.0000, -1.0000, -1.0000, -0.9999, -0.9999, -0.9997, -0.9993,
        -0.9985, -0.9967, -0.9926, -0.9837, -0.9640, -0.9217, -0.8337, -0.6640,
        -0.3799,  0.0000,  0.3799,  0.6640,  0.8337,  0.9217,  0.9640,  0.9837,
         0.9926,  0.9967,  0.9985,  0.9993,  0.9997,  0.9999,  0.9999,  1.0000,
         1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000])


In [5]:
print(torch.relu(a))

tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.4000,  0.8000,  1.2000,  1.6000,  2.0000,  2.4000,
         2.8000,  3.2000,  3.6000,  4.0000,  4.4000,  4.8000,  5.2000,  5.6000,
         6.0000,  6.4000,  6.8000,  7.2000,  7.6000,  8.0000,  8.4000,  8.8000,
         9.2000,  9.6000, 10.0000])


In [6]:
print(F.softmax(a,dim=0))

tensor([6.7952e-10, 1.0137e-09, 1.5123e-09, 2.2561e-09, 3.3657e-09, 5.0210e-09,
        7.4905e-09, 1.1174e-08, 1.6670e-08, 2.4869e-08, 3.7101e-08, 5.5348e-08,
        8.2569e-08, 1.2318e-07, 1.8376e-07, 2.7414e-07, 4.0897e-07, 6.1011e-07,
        9.1017e-07, 1.3578e-06, 2.0256e-06, 3.0219e-06, 4.5081e-06, 6.7253e-06,
        1.0033e-05, 1.4967e-05, 2.2329e-05, 3.3311e-05, 4.9694e-05, 7.4134e-05,
        1.1060e-04, 1.6499e-04, 2.4613e-04, 3.6719e-04, 5.4778e-04, 8.1719e-04,
        1.2191e-03, 1.8187e-03, 2.7132e-03, 4.0476e-03, 6.0383e-03, 9.0081e-03,
        1.3438e-02, 2.0048e-02, 2.9908e-02, 4.4617e-02, 6.6561e-02, 9.9298e-02,
        1.4813e-01, 2.2099e-01, 3.2968e-01])


In [7]:
print(torch.softmax(a,dim=0))

tensor([6.7952e-10, 1.0137e-09, 1.5123e-09, 2.2561e-09, 3.3657e-09, 5.0210e-09,
        7.4905e-09, 1.1174e-08, 1.6670e-08, 2.4869e-08, 3.7101e-08, 5.5348e-08,
        8.2569e-08, 1.2318e-07, 1.8376e-07, 2.7414e-07, 4.0897e-07, 6.1011e-07,
        9.1017e-07, 1.3578e-06, 2.0256e-06, 3.0219e-06, 4.5081e-06, 6.7253e-06,
        1.0033e-05, 1.4967e-05, 2.2329e-05, 3.3311e-05, 4.9694e-05, 7.4134e-05,
        1.1060e-04, 1.6499e-04, 2.4613e-04, 3.6719e-04, 5.4778e-04, 8.1719e-04,
        1.2191e-03, 1.8187e-03, 2.7132e-03, 4.0476e-03, 6.0383e-03, 9.0081e-03,
        1.3438e-02, 2.0048e-02, 2.9908e-02, 4.4617e-02, 6.6561e-02, 9.9298e-02,
        1.4813e-01, 2.2099e-01, 3.2968e-01])


# mse_loss cross_entorpy_loss

In [8]:
a = torch.rand(4)
print(a)
loss = F.mse_loss(torch.full([4],1),a)
loss

tensor([0.5301, 0.4399, 0.8713, 0.9451])


tensor(0.1385)

In [9]:
a = torch.rand(4,3)

In [10]:
loss = torch.nn.CrossEntropyLoss()

# input, NxC=2x3

input = torch.randn(2, 3, requires_grad=True)

# target, N

target = torch.empty(2, dtype=torch.long).random_(3)
output = loss(input, target)
output.backward()


# torch.autograd.grad  loss .backward 

In [11]:
a = torch.ones(4,5)
w = torch.rand(1,5)
y = torch.ones(4)
pred = a@w.t()
print(pred.shape)
loss = F.mse_loss(y,pred)
print(loss)

torch.Size([4, 1])
tensor(4.6470)


D:\software\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([4, 1])) that is different to the input size (torch.Size([4])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  


In [12]:
res = torch.autograd.grad(loss,[w])
# 没有设定其需要梯度信息，所以PyTorch在建图的时候就没有设置它具有梯度信息。

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [13]:
torch.manual_seed(123)

In [14]:
# method_1
torch.manual_seed(123)
w = torch.rand(1,5)
w.requires_grad_()
print(w)
pred = a@w.t()
loss = F.mse_loss(y,pred)
print(loss)
res = torch.autograd.grad(loss,[w])
print(res)

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740]], requires_grad=True)
tensor(0.6837, grad_fn=<MeanBackward0>)
(tensor([[1.6537, 1.6537, 1.6537, 1.6537, 1.6537]]),)


D:\software\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Using a target size (torch.Size([4, 1])) that is different to the input size (torch.Size([4])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  import sys


In [15]:
# method_2
torch.manual_seed(123)
w = torch.rand(1,5,requires_grad=True)
print(w)
pred = a@w.t()
loss = F.mse_loss(y,pred)
print(loss)
res = torch.autograd.grad(loss,[w])
print(res)

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740]], requires_grad=True)
tensor(0.6837, grad_fn=<MeanBackward0>)
(tensor([[1.6537, 1.6537, 1.6537, 1.6537, 1.6537]]),)


D:\software\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([4, 1])) that is different to the input size (torch.Size([4])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  


In [16]:
# method_3
torch.manual_seed(123)
w = torch.rand(1,5,requires_grad=True)
print(w)
pred = a@w.t()
loss = F.mse_loss(y,pred)
print(loss)
loss.backward()
print(w.grad)#  method_3


tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740]], requires_grad=True)
tensor(0.6837, grad_fn=<MeanBackward0>)
tensor([[1.6537, 1.6537, 1.6537, 1.6537, 1.6537]])


D:\software\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([4, 1])) that is different to the input size (torch.Size([4])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  


In [20]:
x = torch.randn(1,784)
w = torch.randn(10,784)
logit = x@w.t()
loss = F.cross_entropy(logit,torch.tensor([3]))
print(loss)
                

tensor(69.2708)


In [23]:
logit.shape

torch.Size([1, 10])